branch-defaults:
  master:
    environment: udagram-api-env
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: udagram-env
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
